fullname: Node.js application
description: 'Node.js assistant will help you create a basic Node.js application and install its dependencies.'

dependencies:
  - use: super.dependencies
  - rpm:
    - 'node-gyp'
    - 'nodejs-abbrev'
    - 'nodejs-ansi'
    - 'nodejs-archy'
    - 'nodejs-asn1'
    - 'nodejs-assert-plus'
    - 'nodejs-async'
    - 'nodejs-aws-sign'
    - 'nodejs-boom'
    - 'nodejs-child-process-close'
    - 'nodejs-chmodr'
    - 'nodejs-chownr'
    - 'nodejs-cmd-shim'
    - 'nodejs-combined-stream'
    - 'nodejs-config-chain'
    - 'nodejs-cookie-jar'
    - 'nodejs-couch-login'
    - 'nodejs-cryptiles'
    - 'nodejs-ctype'
    - 'nodejs-delayed-stream'
    - 'nodejs-devel'
    - 'nodejs-editor'
    - 'nodejs-forever-agent'
    - 'nodejs-form-data'
    - 'nodejs-fstream'
    - 'nodejs-fstream-ignore'
    - 'nodejs-fstream-npm'
    - 'nodejs-github-url-from-git'
    - 'nodejs-graceful-fs'
    - 'nodejs-hawk'
    - 'nodejs-hoek'
    - 'nodejs-http-signature'
    - 'nodejs-inherits'
    - 'nodejs-ini'
    - 'nodejs-init-package-json'
    - 'nodejs-json-stringify-safe'
    - 'nodejs-lockfile'
    - 'nodejs-lru-cache'
    - 'nodejs-mime'
    - 'nodejs-minimatch'
    - 'nodejs-ms'
    - 'nodejs-mute-stream'
    - 'nodejs-node-uuid'
    - 'nodejs-nopt'
    - 'nodejs-normalize-package-data'
    - 'nodejs-npm-registry-client'
    - 'nodejs-npm-user-validate'
    - 'nodejs-npmconf'
    - 'nodejs-npmlog'
    - 'nodejs-oauth-sign'
    - 'nodejs-once'
    - 'nodejs-opener'
    - 'nodejs-osenv'
    - 'nodejs-packaging'
    - 'nodejs-promzard'
    - 'nodejs-proto-list'
    - 'nodejs-qs'
    - 'nodejs-read'
    - 'nodejs-read-installed'
    - 'nodejs-read-package-json'
    - 'nodejs-request'
    - 'nodejs-retry'
    - 'nodejs-rimraf'
    - 'nodejs-semver'
    - 'nodejs-sha'
    - 'nodejs-sigmund'
    - 'nodejs-slide'
    - 'nodejs-sntp'
    - 'nodejs-tar'
    - 'nodejs-tunnel-agent'
    - 'nodejs-uid-number'
    - 'nodejs-which'
    - 'v8', 'v8-devel'
  #- npm: ['glob']

dependencies_vim:
- use: vim.dependencies

args:
  name:
    use: common_args

  github:
    use: common_args

files:
  appnodejs: &appnodejs
    source: .

run:
- $dirname~: $(dirname "$name")
- $basename~: $(basename "$name")
- if $(test -e "$name"):
  - log_e: '$name already exists, cannot proceed.'
- cl: cp -r *appnodejs "$basename"
- dda_c: "$basename"
- cl: cd "$basename"
- log_i: 'Creating Node.js project $basename in $dirname ...'
- use: git.init_add_commit.run
- if defined $github:
  - github: create_and_push
- log_i: 'Node.js project $basename in $dirname has been created.'
- log_i: 'To run the application use: node app.js'
- log_i: 'For more information about Node.js project visit https://nodejs.org'
